# Use the latest Node.js LTS image as base
FROM node:lts

# Set working directory
WORKDIR /app

# Copy the files from the host machine to the container
COPY . .

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install project dependencies
RUN npm install

# Expose port 4200
EXPOSE 4200

# Command to start the Angular development server
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
